name: .NET CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore backend/parte core/finalCore/finalCore.csproj

    - name: Build
      run: dotnet build --configuration Release backend/parte core/finalCore/finalCore.csproj

    - name: Test
      run: dotnet test --no-build --verbosity normal
