name: Configuraci贸n de Entorno .netCore

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Configurar el entorno de .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '20.5'  # Especifica la versi贸n de Node.js que necesitas
     
    - name: Verificar versi贸n de .NET Core
      run: dotnet --version

    - name: Compilar la aplicaci贸n
      run: dotnet build --configuration Release

    - name: Ejecutar pruebas
      run: dotnet test
     
