name: Instalación de Dependencias netCore

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install-dependencies:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código fuente
      uses: actions/checkout@v2  # Asegurarse de que el código fuente se haya clonado

    - name: Configuración de entorno de .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.x  # Especifica la versión de .NET Core que necesitas

    - name: Restaurar paquetes NuGet
      run: dotnet restore
      working-directory: ProyectoCore  # Asegúrate de que esto apunte al directorio de tu proyecto

    - name: Compilar la aplicación
      run: dotnet build --configuration Release
      working-directory: ProyectoCore  # Asegúrate de que esto apunte al directorio de tu proyecto
