name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore BackEnd/Core/finalCore/finalCore.csproj

    - name: Build
      run: dotnet build --configuration Release BackEnd/Core/finalCore/finalCore.csproj

    - name: Run tests
      run: dotnet test --no-build --verbosity normal BackEnd/Core/finalCore/finalCore.csproj
